baseURL = "https://mir7b.github.io/"
url = "https://mir7b.github.io/"
DefaultContentLanguage = "en"
title = "Testing website"
description = ""
theme = "minimal"
source = "/home.md"
lsi = false
safe = true
incremental = false

[Author]
  name = "L"
  meta_author = "L"
  disqus_shortname = "L"
  
[gist]
  noscript = false

[Params]
  description = ""
  highlight = true
  math_engine = "mathjax"
  highlight_style = "github-gist"
  subtitle = "testing stuff"
  logo = "img/portfolio/blue1.png" 
