lsi: false
safe: true
source: /
url: https://mir7b.github.io/ 
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

logo: /img/portfolio/logo
description: no idea
theme: minimal