baseURL = "https://mir7b.github.io/"
url = "https://mir7b.github.io/"
DefaultContentLanguage = "en"
title = "Some Testing Website"
description = ""
theme = "minimal"
source = "/"
lsi = false
safe = true
incremental = false
logo = "/img/portfolio/blue1.png" 

[Author]
  name = "L"
  meta_author = "L"
  disqus_shortname = "L"
  
[gist]
  noscript = false

[Params]
  description = "no idea"
  highlight = true
  math_engine = "mathjax"
  highlight_style = "github-gist"
  subtitle = "testing stuff"
  title = "Some Testing Website"
  theme = "minimal"
  logo = "/img/portfolio/blue1.png" 

  
