baseURL = "https://mir7b.github.io/"
url = "https://mir7b.github.io/"
DefaultContentLanguage = "en"
title = "Some Testing Website"
description = ""
theme = "minimal"
source = "/"
lsi = false
safe = true
incremental = false
logo = "/img/portfolio/blue1.png" 

[gist]
  noscript = false

[Params]
  description = "no idea"
  highlight = true
  math_engine = "mathjax"
  highlight_style = "github-gist"

  
