baseURL = "https://mir7b.github.io/"
DefaultContentLanguage = "en"
title = "Testing website"
theme = "beautifulhugo"
source = "/"
lsi = false
safe = true
incremental = false
[gist]
  noscript = false
[kramdown]
  math_engine = mathjax
  syntax_highlighter= rouge

[Params]
  description = ""
  highlight = true
  math_engine = "mathjax"
  highlight_style = "github-gist"


