baseURL = "https://mir7b.github.io/"
url = "https://mir7b.github.io/"
DefaultContentLanguage = "en"
title = "Testing website"
description = ""
theme = "Freelancer"
source = "/"
lsi = false
safe = true
incremental = false
meta_author = "TBA"
disqus_shortname = "Lara"

[gist]
  noscript = false

[Params]
  description = ""
  highlight = true
  math_engine = "mathjax"
  highlight_style = "github-gist"


