baseURL = "/"
title = "Testing website"

[params]
  description = ""
  highlight = true
  math_engine = "mathjax"
  highlight_style = "github-gist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

